version: '3'

services:
  flyway:
    build:
      dockerfile: ./Dockerfile
      context: Migration-Service
    image: flyway
    container_name: flyway
    networks:
      - backend
    volumes:
      - /root/.m2:/root/.m2
    ports:
      - "8100:8100"

  eureka-server:
    build:
      dockerfile: ./Dockerfile
      context: Eureka-Server
    image: eureka-server
    container_name: eureka-server
    networks:
      - backend
    ports:
      - "8761:8761"

  auth-service:
    build:
      dockerfile: ./Dockerfile
      context: Authentication-Service
    image: auth-service
    container_name: auth-service
    depends_on:
      - eureka-server
    networks:
      - backend
    ports:
      - "8081:8081"

  file-export-service:
    build:
      dockerfile: ./Dockerfile
      context: File-Export-Service
    image: file-service
    container_name: file-service
    depends_on:
      - eureka-server
    networks:
      - backend
    ports:
      - "8090:8090"

  gateway:
    build:
      dockerfile: ./Dockerfile
      context: Gateway
    image: gateway
    container_name: gateway
    depends_on:
      - auth-service
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend: