spring:
  application:
    name: Gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

gateway:
  routes:
    - id: authentication-service
      path: /api/authentication/**
      uri: lb://authentication-service
    - id: kanban-service
      path: /api/kanban/**
      uri: lb://kanban-service

server:
  port: 8080
