spring:
  application:
    name: Gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

gateway:
  routes:
    - id: authentication-service
      path: /api/authentication/**
      uri: lb://authentication-service
    - id: file-export-service
      path: /api/file-export
      uri: lb://file-export-service

server:
  port: 8080
