spring:
  application:
    name: Authentication-Service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/TeamUp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: my.teamup.platform@gmail.com
    password: pkfqcauuhwmitfzg
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    web: debug

server:
  port: 8081

token:
  secret:
    key: cf1865657815ab5bfeb6305237a776a5a3390e083c78779c722bcd3ccf679cdda2f1e3e8d93e56842c55fcfccb5bd7bb41424dc3f8d0d9c984eadb9ececb1562