spring:
  application:
    name: Edit-Profile-Service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hack2024
    username: postgres
    password: PosTer231
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      #defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    web: debug

server:
  port: 8083

token:
  secret:
    key: cf1865657815ab5bfeb6305237a776a5a3390e083c78779c722bcd3ccf679cdda2f1e3e8d93e56842c55fcfccb5bd7bb41424dc3f8d0d9c984eadb9ececb1562