spring:
  application:
    name: File-Export-Service
  datasource:
    url: jdbc:postgresql://uwu-devcrew.ru:5432/Hackaton2024
    username: Hackaton2024
    password: eqwfmoijmoiweqfiomegwjoigbrwejoiebrhjiuhiwvdchuiowdcvopjisxdcvoliknvsripuniouwevrhnuiovwrehiup
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


server:
  port: 8090